pipeline {
    agent any

    stages {
        stage('Clone repo') {
            steps {
                git branch: 'main', url: 'https://github.com/yoabhishekk/DevOps-Project-Two-Tier-Flask-App-main.git'
            }
        }
        
        stage('Deploy with docker compose') {
            steps {
                // This tells Jenkins to step inside the nested folder before running Docker
                dir('DevOps-Project-Two-Tier-Flask-App-main') {
                    
                    // Stop existing containers safely
                    sh 'docker compose down || true'
                    
                    // Build the new image and spin up the containers
                    sh 'docker compose up -d --build'
                }
            }
        }
        
        stage('Cleanup') {
            steps {
                // Removes old, untagged images to save disk space
                sh 'docker image prune -f'
            }
        }
    }
}
